### PR TITLE
Face detection and tracking using Vision

### PR DESCRIPTION
**Pull request by blurtime**
Hi @Silence-GitHub,

first of all, I am still very grateful for this library. Thank you for making it open-source. You'll be at the very first place of people I am going to thank in the licenses of my app. Anyways:

Please read the descriptions of the commits. 
Unfortunately, I forgot to `import Vision` in `CameraFilterVC.swift` so that needs to be done, too (besides calling the function activating the face detection).

I am using callbacks to handle the face detection and then "zoom" in on it - thereby tracking it. If there's more than one face, it will zoom in on the biggest one. It currently can't keep up with the face tracking of e.g. TikTok which is working a lot smoother. It would be VERY(!) great if one could apply a `BBMetalCropFilter` and _then_ change its `BBMetalRect` (or `BBMetalPosition` in other filters) in a short animation - lasting e.g. the average frame duration which would make it look a lot smoother and probably almost as smooth as TikTok's face tracking ([watch this for reference](https://www.youtube.com/watch?v=rECUkcBL-DA)). I am now leveling the new `BBMetalRect` with the previous 2 rects which is giving me a dramatically better result than simply applying the rect immediately. 

Anyway, while working with the `BBMetalCropFilter` I found that the resulting file doesn't look like the preview you see in the `metalView`. It would be great if there were a filter that would make it look like that; such that the resulting video file, firstly, also has the same resolution (say 1080x1920) and, secondly, looks like what you are recording (see first reference). 

There is a lot more potential for filters using Vision. For instance, a filter looking at the distance of objects (or body position) could filter out everything in the back (or everything not human) such that one could put a color or even a picture (from the library) in the background while "reacting" to it ([look here for reference](https://www.youtube.com/watch?v=yDl2BoH0Q5A)). 

Another idea would be a filter taking the position from the index finger's tip ([or the nose](https://www.youtube.com/watch?v=nuLyu9LxxoM)) enabling the user to draw without touching the screen. 

I could provide all the positions using Vision but the filters would probably be a tad too much for me. So if you have time, maybe you could look into this(?). 

Another very cool feature would be if one could apply videos (with varying alpha) as filters so that one could do things like this (background of people partying & changing colors as shown [in this video at 1:12](https://www.youtube.com/watch?v=dXfZnKq8twQ)).

### CODE REVIEW

**Comment by blurtime** [comment]
After discovering in another issue that the `BBMetalRect` of the `BBMetalCropFilter ` was public (which I of course missed) I modified the code to make it smoother - and I managed to improve the smoothness dramatically. I'll try to add the code as soon as possible.

**Comment by Silence-GitHub** [comment]
Thanks for your PR and great idea! Your code helps me a lot.

I did some modification. Now `BBMetalCamera` and `BBMetalVdieoSource` have `preprocessVideo` block to process each video `CMSampleBuffer`. We can detect face in the block.

About smoothness. I tested `Vision` face detection on iPhone 7 iOS `13.5.1`. It takes more than 0.05s to process a 1920x1080 size video frame. It's too slow and the frame rate could not reach 30 per second. I think it's the main reason of not smooth. Did you test the `Vision` face detection duration on your devices? If you did, please share the results.

About crop filter. After cropping, the preview and the resulting video file look different. Because they have different size. To solve it, we should crop a region with the same aspect ratio of resulting video file, and then resizing the cropped texture to the same size of resulting video file. For example, the resulting video file has video size 1920x1080, so the aspect ratio is 16:9. We should always crop a region with aspect ratio 16:9, like size 160x90. And then resizing the cropped texture to size 1920x1080.

**Comment by blurtime** [comment]
@Silence-GitHub Awesome! Happy you like it!

Maybe one could use only every second frame on slower devices? What would you say? I only tested it on my iPhone 11 and it works fine there (obviously faster processor).

I'm still tweaking the code for the smoothness so I might contribute that later. Regarding the filter: Do you have time to add it in the near future? I currently have no knowledge about metal filters besides slowly learning how to apply them. 

I also managed to create a heat map for the foreground of [the same filter I showed you in the initial pull request](https://www.youtube.com/watch?v=yDl2BoH0Q5A) (the background is an image and the foreground the person) by following [this tutorial](https://www.raywenderlich.com/5807038-saliency-analysis-in-ios-using-vision). So it would be great if we could somehow implement that, too. I'll create a new pull request for this new filter and provide the heat map. Do you know how to write a filter for this, too? It would be great if one could not only put an image in the background but also a video (by aligning the frames) and therefore layering a video (or an image) under the heat-mapped frames.

Looking forward to hearing from you!

**Comment by blurtime** [comment]
Hi @Silence-GitHub 
I've now tried to apply the transform filter you recently added and it kinda works but it tends to get pretty slow while not being as accurate as ARKit. I don't even want to imagine how slow it would be on slower devices than mine. The transform filter on top of the cropping filter seems to be just a tad too much. I guess there won't be a way around ARKit if one wants to introduce smooth face tracking and perhaps even something along the lines of face mask filters. 
The object tracking seems to works well, though, and it should be possible to achieve the [effect/filter I mentioned somewhat often recently](https://www.youtube.com/watch?v=yDl2BoH0Q5A) (e.g. in my last comment). The preprocess closure is awesome. I'll create a pull request tomorrow and you can decide whether you would like to create maybe one filter for putting an image in the background and one filter for putting a video in the background (by aligning the frames).

**Comment by Silence-GitHub** [comment]
@blurtime Hi
I need more information about transform filter. Have you test other filters? Are you sure it is the transform filter making camera slow?

**Comment by blurtime** [comment]
Hello @Silence-GitHub 
as you've seen in the pull request, I used to create a new `BBMetalRect` and then apply an entirely new `BBMetalCropFilter` with this new `BBMetalRect` for every new frame. Afterward, I discovered that the `rect` was public and I could just change it in the existing (already applied) `BBMetalCropFilter` instead of re-applying a new `BBMetalCropFilter` again - which I did. Now I put a `BBMetalTransformFilter` on top of `BBMetalCropFilter` but have to adjust the transform every time I change the rect width which happens whenever a new frame enters the preprocess closure.

Accordingly, my code basically looks like this:

    let newWidth = self.cropFilter.rect.width + Float(dWidth) // dWidth denoting the difference in width I want to apply
    let newTransformFactor = CGFloat(1 / newWidth)
    // check if newWidth, newHeight, newX, newY are ok (i.e. all must be <= 1)
    self.cropFilter.rect.width  = newWidth // same for newHeight, newX, newY
    self.transformFilter.transform = CGAffineTransform(scaleX: newTransformFactor, y: newTransformFactor)

With this transform on top of the crop, it tends to get pretty slow. Moreover, the resulting video file often has a shaky black line on the right edge since the transform doesn't seem to be applied quick enough such that the transform is sometimes too small from the width of the previous frame. 

One could tackle this particular problem by changing the width (and therefore the transform) only if the width in the new frame changes dramatically (essentially setting a threshold) and keep it static for the rest of the time (therefore keeping the transform static, too). But the threshold makes the face tracking exceptionally laggy. I've tried lots of things now to make it look smooth but you reach a point where you can't get better face tracking only using `Vision`. I would say there's no way around ARKit if we want to get some seriously accurate and smooth face tracking. Vision tends to be too shaky in my opinion to achieve this. I'd like to be proven wrong but this is my conclusion from having invested lots of time and effort now.  

So if you have lots of free time at some point, you could think about implementing ARKit for version 2.0 and become a competitor of [`ARVideoKit`](https://github.com/AFathi/ARVideoKit) by claiming you're faster at applying metal filters. But that is just an idea. I will continue using your library since ARKit isn't that important in my project. It would've been cool for the face tracking but at least the object tracking works well and should be no problem to handle (I'll create an issue for that and provide the code for the heat-map).

**Pull request merged**
